scalar JSON
scalar DateTime
scalar Number
scalar Upload

type Error @key(fields: "field"){
  field: String!
  message: String!
}
type ApiResponse @key(fields: "message"){
  message: String
  error: Error
}
type Account @key(fields: "id") {
  id: ID
  name: String
  phone: String
  email: String  
  idNumber: Number
  createdAt: DateTime
  updatedAt: DateTime
}

# end of type definitions
# beginning of input type definitions
input SignUpWalletInput {
  name: String!
  phone: String!
  email: String
  password: String!
  address: String
  idNumber: String
}


# end of input type definitions
# beginning of enum definitions
enum AccountType {
  SUPER_ADMIN
  USER
}
